name: Validate translation files
on:
  push:
    branches: [l10n_master]
    paths-ignore:
    - 'po/*/lol.po'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate .po files
        uses: Tar-Minyatur/gettext-validation@master
        with:
          folder: po/
