name: Validate translation files
on:
  push:
    branches: [l10n_master]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate .po files
        uses: Tar-Minyatur/gettext-validation@master
        with:
          folder: po/
          paths-ignore: 
          - 'po/common/lol.po' 
          - 'po/openfoodfacts/lol.po'
          - 'po/openpetfoodfacts/lol.po'
          - 'po/openproductsfacts/lol.po'
          - 'po/openbeautyfacts/lol.po'
          - 'po/tags/lol.po'
